on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run release-please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple
          versioning-strategy: always-bump-patch

      - name: Update release PR with alpha keyword
        if: steps.release-please.outputs.release_created == 'true'
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open --head release-please --json number --jq '.[0].number')
          if [[ -n "$PR_NUMBER" ]]; then
            gh pr edit $PR_NUMBER --body "$(gh pr view $PR_NUMBER --json body --jq '.body')\n\n[alpha]"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}