name: Test Config Flow

on:
  push:
    branches:
      - test_config_flow
      - main
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest homeassistant pytest-asyncio pymodbus pytest-homeassistant-custom-component pytest-mock voluptuous pytest-asyncio scapy

      - name: Run Tests
        run: |
          pytest
